### ISSUE TITLE
Setup tracking for requests for assistance

### ISSUE THREAD

**Issue by jaketrent** [pluralsight/design-system#571]
- [x] Decide what we track
- [x] Aggregate previous period of requests - GH issues, slacks
- [x] Create tracker
- [x] Design timelines around comparisons
- [x] Consider future automation
